name: IOTD

on:
  workflow_dispatch:
  schedule:
    # Runs the workflow once every day at 02:25 UTC
    - cron: "25 2 * * *"

env:
  COMMIT_BRANCH: "gh-pages"

jobs:
  commit_new_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ env.COMMIT_BRANCH }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - name: Generates image
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          SAVE_RESPONSE: False
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python painter.py
        shell: bash

      - name: Configure Git
        run: |
          git config user.name "painter[bot]"
          git config user.email "41895282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push file
        run: |
          git add .
          git commit -m 'new image generated'
          git push origin ${{ env.COMMIT_BRANCH }}
