name: IOTD

on:
  workflow_dispatch:
  schedule:
    # Runs the workflow once every day at 02:25 UTC
    - cron: "25 2 * * *"

jobs:
  commit_new_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
      - name: Get files
        shell: bash
        run: |
          git fetch origin gh-pages:gh-pages --depth=1
          git checkout gh-pages -- iotd/data.json

      - name: Generates image
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          SAVE_RESPONSE: False
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python painter.py
        shell: bash

      - name: Git push
        uses: rsb-23/actions/git-push@main
        with:
          git_user: "painter[bot]"
          files: "iotd/"
          commit_message: "new image generated"
          branch: "gh-pages"
