name: Sync to Pages Branch

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'pages/**'

permissions:
  contents: write
env:
  PAGE_BRANCH: "gh-pages"

jobs:
  sync-to-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout page branch
        uses: rsb-23/actions/checkout@v1
        with:
          ref: ${{ env.PAGE_BRANCH }}

      - name: Configure Git
        run: |
          git config --global user.name "page-sync[bot]"
          git config --global user.email "page-sync[bot]@users.noreply.github.com"

      - name: Copy files from main branch
        run: |
          git checkout main -- pages/
          mv pages/* .
          rmdir pages

      - name: Commit and push changes
        id: changes
        run: |
          git add .
          if git diff --quiet HEAD; then
            echo "No changes detected"
          else
            git commit -m "🔄 Sync pages from main branch"
            git push origin ${{ env.PAGE_BRANCH }}
          fi
